name: Deploy to Cloud run
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
    
    

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
    - name: Run deploy script
      run: |
        chmod +x deploy.sh
        ./deploy.sh
