name: Deploy Auto
on:
  push:
    branches:
    - main
    

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/52282207963/locations/global/workloadIdentityPools/deploy-pool/providers/deploy-provider'
        service_account: 'a123456@optimal-life-378201.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'getTasks'
        runtime: 'python310'
        region: 'australia-southeast1'
